# General Settings
name: Elijah Bernstein-Cooper
title: Elijah Bernstein-Cooper | Blog
job_title: Data Manager
email: elijah@ezbc.me
description: Elijah Bernstein-Cooper is a data manager and data engineer for business problems.
meta_description: Elijah Bernstein-Cooper is a data manager and engineer for business problems. Explore Elijah's portfolio of technology solutions.
avatar: /media/avatar.jpg
favicon: /favicon.ico
analytics_code: UA-XXXXXXX-2
disqus: httpezbcme

# Metadata for search engines
keywords: technology, data engineer, data analysis, data management

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/elijahbernsteincooper/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/ezbc' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 0
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: 
canonical_url: "http://localhost:4000"
baseurl:
environment: local

# Includes
include: ["_pages"]

# Outputting
permalink: /:year/:month/:day/:title
category_dir: categories

# Pagination
pagination:
  enabled: true
  sort_reverse: true
  permalink: '/page/:num/'

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# files in _site directory to keep
keep_files: [media, files]

# files in root to exclude from build
exclude:
  - scripts
  - docker*

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

# plugins
plugins:
  - jekyll-seo-tag

# highlighting
highlighter: rouge

